version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:agxD4KzysXdTeyCuydW3aw4TikEVXNYHyxuwtzTiaBk"
      - checkout
      - run: 
          name: List directory contents
          command: |
            echo "Project root:"
            ls -la
            echo "Test directory:"
            ls -la test || echo "No test directory found"
      - run: npm ci
      - run: npm test
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:QLNm9IdEotAwQqFkhrlBzbXbsbigOOnGOCP0wbc5u2U"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@54.75.117.188 "cd ~/devops && git pull origin main"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@54.75.117.188 "cd ~/devops && npm install"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@54.75.117.188 "cd ~/devops && pm2 describe mathapp > /dev/null && if [ \$? -eq 0 ]; then pm2 restart mathapp; else pm2 start ~/devops/bin/www --name mathapp; fi"
            ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@54.75.117.188 "pm2 save"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main